language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
    - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
    - sudo apt-get update  -qq
    - sudo apt-get install -qq -y libsdl2-dev libsdl2-image-dev
    - sudo apt-get install -qq -y libunittest++-dev

install:
    - cmake CMakeLists.txt
    - make

script:
    - ./tiledlTest

branches:
    only:
        - master
